apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongodb-integration-secret
stringData:
  config.json: |
    {
        "redisHost": "redis-master",
        "redisPort": 6379,
        "redisPassword": "{{ index .Values.secret "redis-password" }}",
        "disableWrite": false,
        "cleanMongoDB": false,
        "mongoUrl": "{{ index .Values.secret "kano-db-url" }}",
        "gRPCServer": "chirpstack:8080",
        "apiToken": "{{ index .Values.secret "grpc_token" }}",
        "logLevel": "debug"
    }
